// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://www.phptravels.net/flights");
    driver.manage().window().setSize(new Dimension(1293, 693));
    driver.findElement(By.id("one-way")).click();
    driver.findElement(By.id("autocomplete")).click();
    driver.findElement(By.id("autocomplete")).sendKeys("den");
    driver.findElement(By.cssSelector(".autocomplete-result:nth-child(1) strong")).click();
    driver.findElement(By.id("autocomplete2")).click();
    driver.findElement(By.id("autocomplete2")).sendKeys("lax");
    driver.findElement(By.cssSelector(".autocomplete-result:nth-child(1) strong")).click();
    driver.findElement(By.id("departure")).click();
    driver.findElement(By.cssSelector(".datepicker:nth-child(20) > .datepicker-days .next > .icon")).click();
    driver.findElement(By.cssSelector(".datepicker:nth-child(20) > .datepicker-days .next > .icon")).click();
    driver.findElement(By.cssSelector(".datepicker:nth-child(20) > .datepicker-days .next > .icon")).click();
    driver.findElement(By.cssSelector(".datepicker:nth-child(20) tr:nth-child(2) > .day:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".guest_flights"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".guest_flights")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(1) .qtyDec > .la")).click();
    driver.findElement(By.cssSelector(".ladda-label")).click();
  }
}
